package com.lirouti.domain.notification.enums;

/** 클라이언트 화면 이동과 문구 선택에 사용하는 알림 사건 유형이다. */
public enum NotificationType {
    PERSONAL_ROUTINE_REMINDER,
    PERSONAL_ROUTINE_DEADLINE,
    PERSONAL_ROUTINE_MISSED,
    CHALLENGE_VERIFICATION_LIKED,
    CHALLENGE_CYCLE_STARTED,
    CHALLENGE_RESTRICTED,
    CHALLENGE_REVIEW_APPROVED,
    CHALLENGE_REVIEW_REJECTED,
    GROUP_MEMBER_JOINED,
    GROUP_VERIFICATION_LIKED,
    GROUP_VERIFICATION_DISAPPOINTED,
    GROUP_MEMBER_POKED,
    GROUP_ROUTINE_UPDATED,
    GROUP_CHAT_MESSAGE,
    GROUP_ROUTINE_STARTED,
    GROUP_ROUTINE_DEADLINE,
    GROUP_ROUTINE_ENDED,
    GROUP_MEMBER_VERIFIED
}
